CREATE TABLE move_data (
    Username TEXT,
    Game_date TEXT,
    Engine_depth SMALLINT,
    Game_number SMALLINT,
    Move_number SMALLINT,
    Move TEXT,
    Move_eval SMALLINT,
    Best_move TEXT,
    Best_move_eval SMALLINT,
    Move_eval_diff SMALLINT,
    Move_accuracy REAL,
    Move_type TEXT,
    Piece TEXT,
    Move_colour TEXT,
    Castling_type TEXT,
    White_castle_num SMALLINT,
    Black_castle_num SMALLINT,
    Move_time REAL
)