mysql:
  create_game_table:
    file_path: "./betterchess/utils/sql/mysql/create_game_table.sql"

  create_move_table:
    file_path: "./betterchess/utils/sql/mysql/create_move_table.sql"

  create_pgn_table:
    file_path: "./betterchess/utils/sql/mysql/create_pgn_table.sql"

  drop_game_table:
    file_path: "./betterchess/utils/sql/mysql/drop_game_table.sql"

  drop_move_table:
    file_path: "./betterchess/utils/sql/mysql/drop_move_table.sql"

  drop_pgn_table:
    file_path: "./betterchess/utils/sql/mysql/drop_pgn_table.sql"

  select_game_data_all:
    file_path: "./betterchess/utils/sql/mysql/select_game_data_all.sql"

  select_game_data:
    file_path: "./betterchess/utils/sql/mysql/select_game_data.sql"

  select_move_data_all:
    file_path: "./betterchess/utils/sql/mysql/select_move_data_all.sql"

  select_move_data:
    file_path: "./betterchess/utils/sql/mysql/select_move_data.sql"

  select_pgn_data_all:
    file_path: "./betterchess/utils/sql/mysql/select_pgn_data_all.sql"
    
  select_pgn_data:
    file_path: "./betterchess/utils/sql/mysql/select_pgn_data.sql"

sqlite:
  create_game_table:
    file_path: "./betterchess/utils/sql/sqlite/create_game_table.sql"

  create_move_table:
    file_path: "./betterchess/utils/sql/sqlite/create_move_table.sql"

  create_pgn_table:
    file_path: "./betterchess/utils/sql/sqlite/create_pgn_table.sql"

  drop_game_table:
    file_path: "./betterchess/utils/sql/sqlite/drop_game_table.sql"

  drop_move_table:
    file_path: "./betterchess/utils/sql/sqlite/drop_move_table.sql"

  drop_pgn_table:
    file_path: "./betterchess/utils/sql/sqlite/drop_pgn_table.sql"

  select_game_data_all:
    file_path: "./betterchess/utils/sql/sqlite/select_game_data_all.sql"

  select_game_data:
    file_path: "./betterchess/utils/sql/sqlite/select_game_data.sql"

  select_move_data_all:
    file_path: "./betterchess/utils/sql/sqlite/select_move_data_all.sql"

  select_move_data:
    file_path: "./betterchess/utils/sql/sqlite/select_move_data.sql"

  select_pgn_data_all:
    file_path: "./betterchess/utils/sql/sqlite/select_pgn_data_all.sql"
    
  select_pgn_data:
    file_path: "./betterchess/utils/sql/sqlite/select_pgn_data.sql"
